# Generated by Django 3.0.3 on 2020-10-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingid', models.CharField(max_length=15)),
                ('customername', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=15)),
                ('modeofpayment', models.CharField(max_length=30)),
                ('billingdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=150)),
                ('modelnumber', models.CharField(max_length=15)),
                ('stock', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Brand')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingid', models.CharField(max_length=15)),
                ('productqty', models.CharField(max_length=20)),
                ('ischeckout', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('cartdate', models.DateField(null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
    ]
