# Generated by Django 3.0.3 on 2020-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rem',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
