# Generated by Django 3.0.3 on 2020-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creationdate',
            field=models.DateField(null=True),
        ),
    ]
