# Generated by Django 3.1.3 on 2020-11-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(max_length=150)),
                ('suppliermob', models.IntegerField(unique=True)),
                ('supplieraddr', models.TextField()),
                ('supplieremail', models.EmailField(max_length=254)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory')),
            ],
        ),
    ]
