# Generated by Django 3.1.3 on 2020-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
